config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :tickets, only: [:create, :show]
  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
    end
    
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
  end
 

  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ApplicationRecord
	belongs_to :train

  validates :number, :top_seats, :bottom_seats, presence: true

  scope :economy, -> { where(type: 'EconomyCarriage') }
  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :ordered, -> { order(:number) }


end

app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
  
end

app/models/economy_carriage.rb
class < Carriage
	validates :side_top_seats, :side_bottom_seats, presence: true
	
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
	validates :title, presence: true

	has_many :trains
	has_many :railway_stations_routes
	has_many :routes, through: :railway_stations_routes

  scope :ordered, -> { joins(:railway_stations_routes).order("railway_stations_routes.position").uniq }

	def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route.try(:position)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end

end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
	belongs_to :railway_station
	belongs_to :route

	validates :railway_station_id, uniqueness: { scope: :route_id }

end

app/models/route.rb
class Route < ApplicationRecord
	has_many :railway_stations_routes
	has_many :railway_stations, through: :railway_stations_routes

	validates :name, presence: true
  validate  :stations_count

	before_validation :set_name

	private

	def set_name
		self.name ||= "#{railway_stations.first.title} - #{railway_stations.last.title}"
	end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least 2 stations")
    end
  end



end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :user
end

app/models/train.rb
class Train < ApplicationRecord
	has_many :carriages
	
  validates :number, presence: true

	belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :tickets
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
    @route = Route.find(params[:id])
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path, notice: "Маршрут удален"
  end


   private
    
    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carriages_controller.rb
class CarriagesController < ApplicationController
  before_action :set_train, only: [:new, :create]

  def new
    @carriage = Carriage.new
  end

  def show
    @carriage = Carriage.find(params[:id])
  end

  def create
    @carriage = @train.carriages.new(carriage_params)

    if @carriage.save
      redirect_to @train
    else
      render :new
    end
  end


  protected
    
  def set_train
    @train = Train.find(params[:train_id])
  end

  def carriage_params
    params.require(:carriage).permit(:number, :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats)
  end
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

      if @railway_station.save
        redirect_to @railway_station, notice: 'Railway station was successfully created.'
      else
        render :new
      end
  end

  def update
      if @railway_station.update(railway_station_params)
        redirect_to @railway_station, notice: 'Railway station was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @railway_station.destroy
    redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:position])
    redirect_to @route
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
    @route = Route.find(params[:id])
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path, notice: "Маршрут удален"
  end


   private
    
    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(:name)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @stations = RailwayStation.all
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_action :authenticate_user!, only: :create

	def show
		@ticket = Ticket.find(params[:id])
	end

	def create
		@ticket = current_user.tickets.new

    if @ticket.save
      redirect_to @ticket
    else
      redirect_to search_path
    end
	end


end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
    @train = Train.find(params[:id])
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path, notice: "Поезд удален"
  end




   private
    
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :current_station_id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

   <div class="field">
    <%= f.label :railway_station_ids %>
    <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @route.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Изменить маршрут</h1>

<%= render 'form' %>
 

<%= link_to 'Назад', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список маршрутов</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to 'Показать', route %></td>
        <td><%= link_to 'Редактировать', edit_route_path(route) %></td>
        <td><%= link_to 'Удалить', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый маршрут' , new_route_path %>

app/views/routes/new.html.erb
<h1>Добавить маршрут</h1>

<%= render 'form' %>
 

<%= link_to 'Назад', routes_path %>

app/views/routes/show.html.erb
<p>
  <strong>Название</strong>
  <%= @route.name %>
</p>
<p>
	<strong>Cтанции:</strong>
	<% if @route.railway_stations.empty? %>
		Список пуст
	<% else %>
		<table>
			<thead>
				<tr>
					<td width="100px">Название</td>
					<td>Позиция</td>
				</tr>
			</thead>
			<tbody>
				<% @route.railway_stations.each do |station| %>
				<tr>
					<td><%= station.title %></td>
					<td>
						<%= form_tag update_position_railway_station_path(station), method: :patch do %>
						<%= number_field_tag :position, station.position_in(@route)  %>
						<%= hidden_field_tag :route_id, @route.id  %>
						<%= submit_tag "Изменить" %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/tickets/show.html.erb
<p>Билет купил: <%= link_to , @ticket.user.email %></p>